name: ssh
version: 1.0.0+0
description: Command line SSH client with dartssh.
# author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/GreenAppers/cruzawl
documentation: https://pub.dev/documentation/dartssh/latest/
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.3.0
  dartssh:
    path: ../
  stack_trace: ^1.10.0
