name: dartssh2
version: 1.1.3-pre
description: A pure dart SSH implementation based on dartssh with bug fixes, up-to-date dependencies and sound null safety.
# author is a deprecated pubspec field.
# author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/TerminalStudio/dartssh2

environment:
  sdk: ">=2.13.0 <3.0.0"

executables:
  dartssh:

dependencies:
  asn1lib: ^1.0.0
  convert: ^3.0.0
  meta: ^1.1.6
  http: ^0.13.3
  pointycastle: ^3.0.0
  validators: ^3.0.0
  pinenacl: ^0.3.3

  # for `dartssh` command
  args: ^2.0.0
  dart_console: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.1
  lints: ^1.0.1
  test: ^1.6.5
