name: dartssh3
version: 3.0.0
description: SSH and SFTP client written in pure Dart, aiming to be feature-rich as well as easy to use.
homepage: https://github.com/vicajilau/dartssh3

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  asn1lib: ^1.5.3
  convert: ^3.1.1
  meta: ^1.15.0
  pointycastle: ^3.9.1
  pinenacl: ^0.6.0

dev_dependencies:
  build_runner: ^2.4.12
  dart_code_metrics_presets: ^2.15.0
  lints: ^4.0.0
  test: ^1.25.8

false_secrets:
  - test
