name: dartssh2
version: 2.2.0
description: A SSH and SFTP client written in pure Dart, aiming to be feature-rich as well as easy to use.
# author is a deprecated pubspec field.
# author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/TerminalStudio/dartssh2

environment:
  sdk: ">=2.14.0 <3.0.0"

executables:
  dartssh:
  dartsftp:

dependencies:
  asn1lib: ^1.0.0
  convert: ^3.0.0
  meta: ^1.1.6
  http: ^0.13.3
  pointycastle: ^3.0.0
  validators: ^3.0.0
  pinenacl: ^0.3.3

  # for `dartssh` and `dartsftp` command
  args: ^2.0.0
  dart_console: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.1
  lints: ^1.0.1
  test: ^1.6.5

false_secrets:
  - test
